name: Update Flow-Based Unemployment Gap

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM UTC
  workflow_dispatch:    # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Cache R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages: |
            any::ggplot2
            any::dplyr
            any::tibble
            any::tidyr
            any::readxl
            any::lubridate
            any::zoo
            any::blsR

      - name: Run script
        env:
          BLS_API: ${{ secrets.BLS_API }}
        run: Rscript u_gap_update.R

      - name: Commit and push updated output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull
          git add output/*.csv output/*.png || echo "No files to add"
          git commit -m "Update unemployment gap data and graphs [automated]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main

