name: Update Flow-Based Unemployment Gap

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM UTC
  workflow_dispatch:    # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::ggplot2
            any::dplyr
            any::readxl
            any::lubridate
            any::zoo
            any::blsR

      - name: Run script
        env:
          BLS_API: ${{ secrets.BLS_API }}
        run: Rscript u_gap_update.R
